name: Add Jira Issue Link to GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  add-jira-link:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira issue key from GitHub issue title or body
        id: extract_key
        run: |
          # Extract Jira issue key with format RECSYS10-[number]
          ISSUE_KEY=$(echo "${{ github.event.issue.title }}${{ github.event.issue.body }}" | grep -oE 'RECSYS10-[0-9]+')
          echo "JIRA_ISSUE_KEY=${ISSUE_KEY}" >> $GITHUB_ENV

      - name: Add Jira issue link to GitHub issue
        if: env.JIRA_ISSUE_KEY != ''
        run: |
          # Define the Jira base URL (customize your Jira URL here)
          JIRA_BASE_URL="https://boostcampaitech7recsys.atlassian.net/browse"

          # Create the full Jira issue link
          JIRA_LINK="${JIRA_BASE_URL}/${{ env.JIRA_ISSUE_KEY }}"

          # Get the current body of the GitHub issue
          ISSUE_BODY="${{ github.event.issue.body }}"

          # Add the Jira issue link at the bottom of the GitHub issue
          UPDATED_BODY="${ISSUE_BODY}\n\nRelated Jira Issue: [${{ env.JIRA_ISSUE_KEY }}](${JIRA_LINK})"

          # Update the GitHub issue with the Jira link
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d "{\"body\": \"$UPDATED_BODY\"}"
